# Generated by Django 3.1.1 on 2020-09-26 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hectare',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.basemodel')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
            bases=('utils.basemodel',),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.basemodel')),
                ('name', models.CharField(max_length=50)),
                ('hectares', models.ManyToManyField(to='field.Hectare')),
            ],
            bases=('utils.basemodel',),
        ),
    ]
