# Generated by Django 3.1.1 on 2020-09-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rain', '0001_initial'),
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='rains',
            field=models.ManyToManyField(related_name='field', to='rain.Rain'),
        ),
        migrations.AlterField(
            model_name='field',
            name='hectares',
            field=models.ManyToManyField(related_name='field', to='field.Hectare'),
        ),
    ]
